### ISSUE TITLE
Add clusterapi + terraform iteration to sharingio/coder:main .sharingio/init

### ISSUE THREAD

**Issue by hh** [sharingio/pair#182]
- [x] Support bringing up coder on pair via .sharingio/init
- [ ] Support bringing up cluster-api on pair via .sharingio/init
- [ ] Support coder template update (pair w/ Ben at Coder to fix 403 error later today)
- [ ] Create new coder terraform templates to support clusterapi

**Comment by hh** [comment]
First part, in pair / shell, deploying cluster-api (with vcluster for the moment):
- [ ] 1. clusterctl init --infrastructure vcluster
- [ ] 2. use kubectl to create vclusters, ingress for kubeapi
- [ ] 3. use kubectl to retrieve kubeconfig
- [ ] 4. ensure kubeconfig can reach cluster
Second part, in standalone terraform:
- [ ] Step 2 from above via https://registry.terraform.io/providers/hashicorp/kubernetes/latest/docs/resources/manifest#example-create-a-kubernetes-custom-resource-definition
- [ ] Step 3 from above via https://registry.terraform.io/providers/hashicorp/kubernetes/latest/docs/data-sources/resource
- [ ] Step 4 deploy some resources (maybe a pair environment)

**Comment by hh** [comment]
With a working clusterapi w/ vcluster, we can use terraform to get a provisioned cluster in 22 seconds.

```
ii@sanskar:~/sharingio/coder/.sharing.io/vcluster$ terraform apply -auto-approve ; kubectl get clusters -n coder-ws vcluster1 -w
kubernetes_namespace.work-namespace: Creating...
kubernetes_namespace.work-namespace: Creation complete after 0s [id=coder-ws]
kubernetes_manifest.cluster_vclusters_vcluster1: Creating...
kubernetes_manifest.vcluster_vclusters_vcluster1: Creating...
kubernetes_manifest.vcluster_vclusters_vcluster1: Creation complete after 1s
kubernetes_manifest.cluster_vclusters_vcluster1: Creation complete after 1s

Apply complete! Resources: 3 added, 0 changed, 0 destroyed.
NAME        PHASE          AGE   VERSION
vcluster1   Provisioning   0s    
vcluster1   Provisioning   22s   
```

**Comment by hh** [comment]
Kubeconfig is available as a secret:
```
ii@sanskar:~/sharingio/coder/.sharing.io/vcluster$ kubectl get secrets -n coder-ws vcluster1-kubeconfig  -o jsonpath={.data.value} | base64 -d | grep -v data:
apiVersion: v1
clusters:
- cluster:
    server: https://vcluster1.coder-ws.svc:443
  name: my-vcluster
contexts:
- context:
    cluster: my-vcluster
    namespace: default
    user: my-vcluster
  name: my-vcluster
current-context: my-vcluster
kind: Config
preferences: {}
users:
- name: my-vcluster
  user:
 ```
