### ISSUE TITLE
Common instance set configuration

### ISSUE THREAD

**Issue by BobyMCbobs** [sharingio/pair#58]
In a `.sharing.io` there should be a configuration file that declares commonly used repos and env.

An proposal for the config file

```yaml
templates:
  - name: Kubernetes testing
    repos:
      - cncf/apisnoop
      - apisnoop/ticket-writing
      - kubernetes/kubernetes
    env:
      - TZ: UTC
      - CUSTOM_ENV: hello
  - name: FlatTrack development
    repos:
      - https://gitlab.com/flattrack/flattrack
```

The file could be called _templates.yaml_.

This would be displayed on the frontend as an optional _set_ on the new instance page.
When selected fields would be populated (such as repos and env).
