### ISSUE TITLE
Declarative init

### ISSUE THREAD

**Issue by BobyMCbobs** [sharingio/pair#60]
It would be best for numerous reasons to replace a _.sharing.io/init_ script with a YAML file.
Such as for:
- portability
- generic features

Common features might include:
- tmate window setup
- removing PowerDNS
- configuring DNS records

This configuration might look something like:

```yaml
prepareCommands:
  - echo my standard prepare command
commands:
  - echo my thing
tmate:
  windows:
    - name: Tilt
      dir: myapp
      commands:
        - tilt up --host 0.0.0.0
    - name: backend
      dir: myapp
      commands:
        - go build
    - name: frontend
      dir: myapp/web
      commands:
        - npm run build

kubernetes:
  namespace: myapp-dev
  useWildcardTLS: true
  removeHostedDNS: false
  dnsConfig:
    - type: TXT
      name: myapp-dns-something
      value:
        - hello
  env:
    - MY_ENV: test
    - MY_APP_SUBDOMAIN: myapp-dev
    - MY_APP_HOSTNAME: "${myapp-dev}:${SHARINGIO_PAIR_BASE_DNS_NAME}"
  prepareCommands:
    - echo my prepare override command
  commands:
    - echo do my thing override
  tmate:
    merge: true
    windows:
      - name: Postgres
        commands:
          - psql "postgres://postgres:postgres@postgres.postgres/postgres"

plain:
  env:
    - POSTGRES_USER: myapp
    - POSTGRES_DATABASE: myapp
    - POSTGRES_PASSWORD: myapp
    - PGUSER: myapp
```

Root level fields like
- prepareCommands
- commands
- tmate

will be overridden by ones declared in _kubernetes_ or _plain_ if _merge_ is _false_.

It might be best to not use a shell script to interpret these values a small Go app would make it easier
